### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by yezongyang** [vinayakjadhav/jR3DCarousel#1]
1.The slide class may have prefix
2.somebody want to hide controlls button

thanks

**Comment by vinayakjadhav** [comment]
Thanks for suggestions @yezongyang.
1. Can you please elaborate more.
2. If someone wants to hide control buttons, just simply add css
.controls {
    display: none!important;
}
To keep the plugin footprint minimal I haven't given that as option.

**Comment by yezongyang** [comment]
using custom template with slide class which is so normal that other plugins (fullpage.js) affect jR3DCarousel.

**Comment by vinayakjadhav** [comment]
ahh..I see.. you mean other plugin is causing problem.. I went through the fullpage.js documentation & slide is used when one wants to have slider in page, So it would be mutually exclusive to jR3DCarousel I guess. Also the jR3DCarousel only takes into consideration the `slide` class which is inside the main container & doesnt have any effect on other `slide` class elements.

**Comment by vinayakjadhav** [comment]
Lets see if `silde` class is too common, then maybe customizable class option could be provided, but then in options, a required option needs to be added something like
 `{..,templateClass: 'myCustom3DSlide',..}`

Let me know what do you think.

**Comment by yezongyang** [comment]
uh, yes, a special template class is better. A required option is flexible for user. Thank you very much!

**Comment by vinayakjadhav** [comment]
ohk.. I would implement that in next release. If you are using in your project can you please share the link (if plausible).. thanks.

**Comment by vinayakjadhav** [comment]
Added 'slideClass' as option to specify the custom slide class in case where html template is used.
e.g. 
                        `{ .., 
                              slideClass: 'jR3DCarouselCustomSlide', ..
            }`
