### ISSUE TITLE
Navigation overspins when left running

### ISSUE THREAD

**Issue by jlarmstrongiv** [vinayakjadhav/jR3DCarousel#2]
If the slideshow loads and is left running for a while, the navigation buttons make the slides spirals rapidly back (instead of going through two revolutions, for instance)

![ezgif-2034387152](https://cloud.githubusercontent.com/assets/20903247/19999859/088747c6-a24b-11e6-9a0e-d8a6e9dc3aec.gif)

**Comment by vinayakjadhav** [comment]
enhanced the plugin.
