### ISSUE TITLE
Loop time

### ISSUE THREAD

**Issue by hortipeter** [vinayakjadhav/jR3DCarousel#4]
Hello, how can stop it the autoplay slide? or slide times settings..

**Comment by vinayakjadhav** [comment]
Hi, yes, just set `autoplay: false` & `animationDuration": 1000, animationInterval: 1200`. 
http://vinayakjadhav.github.io/jR3DCarousel/ when you visit this page , on left you can choose whatever settings you want & from right side you can get the generated code, simple.

**Comment by hortipeter** [comment]
Thanks. But i would like to stop after third loop. I create a google banner. It is necessary to stop after 30 seconds or third 3 loop.

**Comment by vinayakjadhav** [comment]
Ohh okk.. got the issue you are facing.. Here try below code;
`setTimeout( function(){console.log("Pausing after 30s"); myjR3DCarousel.pauseCarousel();}, 30000)`
 Where `myjR3DCarousel` is instance of your carousel.

**Comment by hortipeter** [comment]
Perfect. Thank you. 👍

**Comment by vinayakjadhav** [comment]
You are welcome..
