### ISSUE TITLE
Autoplay when browser tab is active

### ISSUE THREAD

**Issue by ghost** [vinayakjadhav/jR3DCarousel#5]
Please note that when the user changes the browser tab and then comes back to the page with the carousel, autoplay will start, even though the `autoplay` property has been set to `false`.

Cheers,
Davide

**Comment by hortipeter** [comment]
Yes, this is my problem..

**Comment by ghost** [comment]
See lines `233 - 241` (https://github.com/vinayakjadhav/jR3DCarousel/blob/master/src/jR3DCarousel.js#L233-L241), before the `visibilityCheck()` function, it may be helpful to check if the `_setting.autoplay` has been set to `true`. Like that:
```
if(_settings.autoplay){
	visibilityCheck(function(){
		if(visibilityCheck()){
			//console.log("vis")
			_playjR3DCarousel();
		}else{
			//console.log("not vis")
			_pausejR3DCarousel();
		}
	});
}
```

Waiting for the author to update the plug-in, I resolved the issue by pausing the carousel on `window.onfocus`event (using jQuery):
```
$(window).on('focus', function() {
    carousel.pauseCarousel();
});
```

where `carousel` is a reference to the jRDCarousel object:
```
var carousel = $('.jR3DCarouselGalleryCustom').jR3DCarousel({
  autoplay: false
});
```

**Comment by vinayakjadhav** [comment]
Nice catch Davide. Thanks for reporting, @eyeonx @hortipeter I'll update the plugin soon as I have some other things in my mind to improve.
@eyeonx If you dont mind can you please provide the url where you have used the plugin.
-Vinayak

**Comment by vinayakjadhav** [comment]
fixed the issue.. plz refer V1.0.1

**Comment by hortipeter** [comment]
The problem not resolved..

**Comment by hortipeter** [comment]
[jR3DCarousel-minta.zip](https://github.com/vinayakjadhav/jR3DCarousel/files/1054320/jR3DCarousel-minta.zip)

**Comment by vinayakjadhav** [comment]
@hortipeter the issue was for carousel with `autoplay` set to `false` & which is working fine, and in your files you used `autoplay`  to `true` so its working as expected. Please checkout the [Demo](http://vinayakjadhav.github.io/jR3DCarousel) page.

**Comment by hortipeter** [comment]
Yes. When autoplay set to true?
I use true and: `setTimeout( function(){console.log("Pausing after 15s"); jR3DCarousel.pauseCarousel();}, 15000)`

**Comment by vinayakjadhav** [comment]
ohh.. got it.. your issue is different..
@hortipeter Can you please provide me the url where you are using it.
I have one solution for you.. Don't set `autoplay` to `true` initially.. set it `false` & start play manually using public API. `jR3DCarousel.playCarousel();` when its loaded. That should work.

**Comment by hortipeter** [comment]
Public API?
