### ISSUE TITLE
showSlide() method does not work

### ISSUE THREAD

**Issue by abolotin** [vinayakjadhav/jR3DCarousel#6]
Hello :)

1. showSlide() should only works with navigation enabled. If navigation disabled, showSlide() will not work at all. So, may be just hide navigation, using "display:none" or appending class, for example "navigation-hidden", instead of removing it?

2. If navigation enabled, showSlide does not work too.
In code: _jR3DCarouselDiv.find('.nav'). ...
"_jR3DCarouselDiv" object does not contains ".nav" childrens, but _jR3DCarouselDiv.parent().find('.navigation') does.

---
Script version: 1.0.4

Script initiatiation:
$(".jr3dcarousel-gallery").jR3DCarousel({
slideClass: "jr3dcarousel-gallery-image",
...
})

Container:
&lt;ul class="jr3dcarousel-gallery"&gt;
&lt;li class="jr3dcarousel-gallery-image"&gt;&lt;img ... /&gt;&lt;/li&gt;
...
&lt;/ul&gt;

**Comment by abolotin** [comment]
3. Yet another bug: showSlide() indexing begins from 1, not from 0. Replace "(index-1)" by "index"? :)

**Comment by vinayakjadhav** [comment]
@abolotin Thanks for reporting. I'll check

**Comment by vinayakjadhav** [comment]
@abolotin 1.fixed, 2.fixed, 3. its always been starting from 0(ReadMe page).
