### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by philip-j** [vinayakjadhav/jR3DCarousel#7]
Any tips for getting this to work with IE11?  On IE11 the images are small, how can i size them appropriately?  They are the perfect size in all other browsers including Edge.

**Comment by vinayakjadhav** [comment]
Hi Philip, plugin is supported only in modern browsers as 3D effect is involved. Please refer https://caniuse.com/#feat=transforms3d

**Comment by philip-j** [comment]
Hello and thanks for the prompt response.  This explains why I could not
get it to work on IE11.  Thanks again

phil

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
